/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/rook/rook/pkg/apis/noobaa.rook.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNooBaaBucketClasses implements NooBaaBucketClassInterface
type FakeNooBaaBucketClasses struct {
	Fake *FakeNoobaaV1alpha1
	ns   string
}

var noobaabucketclassesResource = schema.GroupVersionResource{Group: "noobaa.rook.io", Version: "v1alpha1", Resource: "noobaabucketclasses"}

var noobaabucketclassesKind = schema.GroupVersionKind{Group: "noobaa.rook.io", Version: "v1alpha1", Kind: "NooBaaBucketClass"}

// Get takes name of the nooBaaBucketClass, and returns the corresponding nooBaaBucketClass object, and an error if there is any.
func (c *FakeNooBaaBucketClasses) Get(name string, options v1.GetOptions) (result *v1alpha1.NooBaaBucketClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(noobaabucketclassesResource, c.ns, name), &v1alpha1.NooBaaBucketClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaBucketClass), err
}

// List takes label and field selectors, and returns the list of NooBaaBucketClasses that match those selectors.
func (c *FakeNooBaaBucketClasses) List(opts v1.ListOptions) (result *v1alpha1.NooBaaBucketClassList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(noobaabucketclassesResource, noobaabucketclassesKind, c.ns, opts), &v1alpha1.NooBaaBucketClassList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NooBaaBucketClassList{ListMeta: obj.(*v1alpha1.NooBaaBucketClassList).ListMeta}
	for _, item := range obj.(*v1alpha1.NooBaaBucketClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nooBaaBucketClasses.
func (c *FakeNooBaaBucketClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(noobaabucketclassesResource, c.ns, opts))

}

// Create takes the representation of a nooBaaBucketClass and creates it.  Returns the server's representation of the nooBaaBucketClass, and an error, if there is any.
func (c *FakeNooBaaBucketClasses) Create(nooBaaBucketClass *v1alpha1.NooBaaBucketClass) (result *v1alpha1.NooBaaBucketClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(noobaabucketclassesResource, c.ns, nooBaaBucketClass), &v1alpha1.NooBaaBucketClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaBucketClass), err
}

// Update takes the representation of a nooBaaBucketClass and updates it. Returns the server's representation of the nooBaaBucketClass, and an error, if there is any.
func (c *FakeNooBaaBucketClasses) Update(nooBaaBucketClass *v1alpha1.NooBaaBucketClass) (result *v1alpha1.NooBaaBucketClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(noobaabucketclassesResource, c.ns, nooBaaBucketClass), &v1alpha1.NooBaaBucketClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaBucketClass), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNooBaaBucketClasses) UpdateStatus(nooBaaBucketClass *v1alpha1.NooBaaBucketClass) (*v1alpha1.NooBaaBucketClass, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(noobaabucketclassesResource, "status", c.ns, nooBaaBucketClass), &v1alpha1.NooBaaBucketClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaBucketClass), err
}

// Delete takes name of the nooBaaBucketClass and deletes it. Returns an error if one occurs.
func (c *FakeNooBaaBucketClasses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(noobaabucketclassesResource, c.ns, name), &v1alpha1.NooBaaBucketClass{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNooBaaBucketClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(noobaabucketclassesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NooBaaBucketClassList{})
	return err
}

// Patch applies the patch and returns the patched nooBaaBucketClass.
func (c *FakeNooBaaBucketClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NooBaaBucketClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(noobaabucketclassesResource, c.ns, name, pt, data, subresources...), &v1alpha1.NooBaaBucketClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaBucketClass), err
}
