/*
Copyright 2018 The Rook Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	nfs_rook_io_v1alpha1 "github.com/rook/rook/pkg/apis/nfs.rook.io/v1alpha1"
	versioned "github.com/rook/rook/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rook/rook/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/rook/rook/pkg/client/listers/nfs/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// NFSServerInformer provides access to a shared informer and lister for
// NFSServers.
type NFSServerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NFSServerLister
}

type nFSServerInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewNFSServerInformer constructs a new informer for NFSServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNFSServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.NfsV1alpha1().NFSServers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.NfsV1alpha1().NFSServers(namespace).Watch(options)
			},
		},
		&nfs_rook_io_v1alpha1.NFSServer{},
		resyncPeriod,
		indexers,
	)
}

func defaultNFSServerInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewNFSServerInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *nFSServerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&nfs_rook_io_v1alpha1.NFSServer{}, defaultNFSServerInformer)
}

func (f *nFSServerInformer) Lister() v1alpha1.NFSServerLister {
	return v1alpha1.NewNFSServerLister(f.Informer().GetIndexer())
}
