/*
Copyright 2018 The Rook Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apiscephrookiov1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	versioned "github.com/rook/rook/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rook/rook/pkg/client/informers/externalversions/internalinterfaces"
	cephrookiov1 "github.com/rook/rook/pkg/client/listers/ceph.rook.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CephFilesystemInformer provides access to a shared informer and lister for
// CephFilesystems. Prefer using the type-safe variant (see [TypedCephFilesystemInformer]).
type CephFilesystemInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cephrookiov1.CephFilesystemLister
}

// TypedCephFilesystemInformer provides access to a shared informer and lister for
// CephFilesystems, including the type-safe TypedInformer variant.
// It is a superset of CephFilesystemInformer.
type TypedCephFilesystemInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() CephFilesystemIndexInformer
	Lister() cephrookiov1.CephFilesystemLister
}

// CephFilesystemIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type CephFilesystemIndexInformer cache.TypedSharedIndexInformer[*apiscephrookiov1.CephFilesystem]

// CephFilesystemHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for CephFilesystem.
type CephFilesystemHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiscephrookiov1.CephFilesystem]

// CephFilesystemDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for CephFilesystem.
type CephFilesystemDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiscephrookiov1.CephFilesystem]

// CephFilesystemFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for CephFilesystem.
type CephFilesystemFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiscephrookiov1.CephFilesystem]

// CephFilesystemIndexers is a specialization of [cache.TypedIndexers] for CephFilesystem.
type CephFilesystemIndexers = cache.TypedIndexers[*apiscephrookiov1.CephFilesystem]

// DeletedCephFilesystem is a specialization of [cache.DeletedObject] for CephFilesystem.
type DeletedCephFilesystem = cache.DeletedObject[*apiscephrookiov1.CephFilesystem]

type cephFilesystemInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCephFilesystemInformer constructs a new informer for CephFilesystem type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCephFilesystemInformer]).
func NewCephFilesystemInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewCephFilesystemInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedCephFilesystemInformer constructs a new informer for CephFilesystem type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCephFilesystemInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers CephFilesystemIndexers) CephFilesystemIndexInformer {
	return NewTypedCephFilesystemInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredCephFilesystemInformer constructs a new informer for CephFilesystem type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredCephFilesystemInformer]).
func NewFilteredCephFilesystemInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedCephFilesystemInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredCephFilesystemInformer constructs a new informer for CephFilesystem type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredCephFilesystemInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers CephFilesystemIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) CephFilesystemIndexInformer {
	return NewTypedCephFilesystemInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewCephFilesystemInformerWithOptions constructs a new informer for CephFilesystem type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCephFilesystemInformerWithOptions]).
func NewCephFilesystemInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedCephFilesystemInformerWithOptions(client, namespace, options)
}

// NewTypedCephFilesystemInformerWithOptions constructs a new informer for CephFilesystem type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCephFilesystemInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) CephFilesystemIndexInformer {
	gvr := schema.GroupVersionResource{Group: "ceph.rook.io", Version: "v1", Resource: "cephfilesystems"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiscephrookiov1.CephFilesystem](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CephV1().CephFilesystems(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CephV1().CephFilesystems(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CephV1().CephFilesystems(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CephV1().CephFilesystems(namespace).Watch(ctx, opts)
			},
		}, client),
		&apiscephrookiov1.CephFilesystem{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *cephFilesystemInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedCephFilesystemInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *cephFilesystemInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *cephFilesystemInformer) TypedInformer() CephFilesystemIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscephrookiov1.CephFilesystem](f.factory.InformerFor(&apiscephrookiov1.CephFilesystem{}, f.defaultInformer))
}

func (f *cephFilesystemInformer) Lister() cephrookiov1.CephFilesystemLister {
	return cephrookiov1.NewCephFilesystemLister(f.Informer().GetIndexer())
}

// ToTypedCephFilesystemInformer converts an untyped informer into a TypedCephFilesystemInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CephFilesystem. If that is not the case, calling type-safe methods of the returned
// TypedCephFilesystemInformer leads to runtime panics. A safer alternative is to pass
// around a TypedCephFilesystemInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedCephFilesystemInformer(informer CephFilesystemInformer) TypedCephFilesystemInformer {
	if informer, ok := informer.(TypedCephFilesystemInformer); ok {
		return informer
	}
	return &cephFilesystemTypedInformerAdapter{informer}
}

type cephFilesystemTypedInformerAdapter struct {
	CephFilesystemInformer
}

func (a *cephFilesystemTypedInformerAdapter) TypedInformer() CephFilesystemIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscephrookiov1.CephFilesystem](a.Informer())
}

// ToCephFilesystemIndexInformer converts an untyped informer into a CephFilesystemIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CephFilesystem. If that is not the case, calling type-safe methods of the returned
// CephFilesystemIndexInformer leads to runtime panics. A safer alternative is to pass
// around a CephFilesystemIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToCephFilesystemIndexInformer(informer cache.SharedIndexInformer) CephFilesystemIndexInformer {
	if informer, ok := informer.(CephFilesystemIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiscephrookiov1.CephFilesystem](informer)
}
