/*
Copyright 2018 The Rook Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	cephrookiov1 "github.com/rook/rook/pkg/client/clientset/versioned/typed/ceph.rook.io/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCephObjectStoreUsers implements CephObjectStoreUserInterface
type fakeCephObjectStoreUsers struct {
	*gentype.FakeClientWithList[*v1.CephObjectStoreUser, *v1.CephObjectStoreUserList]
	Fake *FakeCephV1
}

func newFakeCephObjectStoreUsers(fake *FakeCephV1, namespace string) cephrookiov1.CephObjectStoreUserInterface {
	return &fakeCephObjectStoreUsers{
		gentype.NewFakeClientWithList[*v1.CephObjectStoreUser, *v1.CephObjectStoreUserList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("cephobjectstoreusers"),
			v1.SchemeGroupVersion.WithKind("CephObjectStoreUser"),
			func() *v1.CephObjectStoreUser { return &v1.CephObjectStoreUser{} },
			func() *v1.CephObjectStoreUserList { return &v1.CephObjectStoreUserList{} },
			func(dst, src *v1.CephObjectStoreUserList) { dst.ListMeta = src.ListMeta },
			func(list *v1.CephObjectStoreUserList) []*v1.CephObjectStoreUser {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.CephObjectStoreUserList, items []*v1.CephObjectStoreUser) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
