/*
Copyright 2021 The Rook Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package kms

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"

	"github.com/IBM/go-sdk-core/v5/core"
	kp "github.com/IBM/keyprotect-go-client/ibmkeyprotectapiv2"
	"github.com/pkg/errors"
)

const (
	TypeIBM = "ibmkeyprotect"
	//nolint:gosec // IbmKeyProtectServiceApiKey is the IBM Key Protect service API key
	IbmKeyProtectServiceApiKey = "IBM_KP_SERVICE_API_KEY"
	//nolint:gosec // IbmKeyProtectInstanceIdKey is the IBM Key Protect instance id
	IbmKeyProtectInstanceIdKey = "IBM_KP_SERVICE_INSTANCE_ID"
	//nolint:gosec // IbmKeyProtectBaseUrlKey is the IBM Key Protect base url
	IbmKeyProtectBaseUrlKey = "IBM_KP_BASE_URL"
	//nolint:gosec // IbmKeyProtectTokenUrlKey is the IBM Key Protect token url
	IbmKeyProtectTokenUrlKey = "IBM_KP_TOKEN_URL"

	// ibmKeyProtectKeyType is the MIME type used for Key Protect key resources.
	ibmKeyProtectKeyType = "application/vnd.ibm.kms.key+json"
	// ibmKeyProtectReturnRepresentation asks Key Protect to return the key material and
	// metadata in the response entity-body.
	ibmKeyProtectReturnRepresentation = "return=representation"
	// ibmKeyProtectDefaultTokenURL mirrors the former kp.DefaultTokenURL (the IAM token endpoint).
	// The v2 SDK does not export an equivalent constant.
	ibmKeyProtectDefaultTokenURL = "https://iam.cloud.ibm.com/oidc/token" //nolint:gosec // not a credential, just the IAM token endpoint
)

var (
	kmsIBMKeyProtectMandatoryTokenDetails      = []string{IbmKeyProtectServiceApiKey}
	kmsIBMKeyProtectMandatoryConnectionDetails = []string{IbmKeyProtectInstanceIdKey, IbmKeyProtectServiceApiKey}
	// ErrIbmServiceApiKeyNotSet is returned when IBM_KP_SERVICE_API_KEY is not set
	ErrIbmServiceApiKeyNotSet = errors.Errorf("%s not set.", IbmKeyProtectServiceApiKey)
	// ErrIbmInstanceIdKeyNotSet is returned when IBM_KP_SERVICE_INSTANCE_ID is not set
	ErrIbmInstanceIdKeyNotSet = errors.Errorf("%s not set.", IbmKeyProtectInstanceIdKey)
)

// ibmKeyProtectClient wraps the autogenerated IBM Key Protect v2 SDK client with the
// instance ID and the URLs it was configured with, exposing the few operations Rook needs.
type ibmKeyProtectClient struct {
	api        *kp.IbmKeyProtectApiV2
	instanceID string
	baseURL    string
	tokenURL   string
}

// InitKeyProtect initializes the KeyProtect KMS client using the autogenerated
// "github.com/IBM/keyprotect-go-client/ibmkeyprotectapiv2" SDK and an IAM authenticator.
func InitKeyProtect(config map[string]string) (*ibmKeyProtectClient, error) {
	serviceApiKey := GetParam(config, IbmKeyProtectServiceApiKey)
	if serviceApiKey == "" {
		return nil, ErrIbmServiceApiKeyNotSet
	}

	instanceId := GetParam(config, IbmKeyProtectInstanceIdKey)
	if instanceId == "" {
		return nil, ErrIbmInstanceIdKeyNotSet
	}

	baseUrl := GetParam(config, IbmKeyProtectBaseUrlKey)
	if baseUrl == "" {
		baseUrl = kp.DefaultServiceURL
	}

	tokenUrl := GetParam(config, IbmKeyProtectTokenUrlKey)
	if tokenUrl == "" {
		tokenUrl = ibmKeyProtectDefaultTokenURL
	}

	authenticator := &core.IamAuthenticator{
		ApiKey: serviceApiKey,
		URL:    tokenUrl,
	}

	api, err := kp.NewIbmKeyProtectApiV2(&kp.IbmKeyProtectApiV2Options{
		URL:           baseUrl,
		Authenticator: authenticator,
	})
	if err != nil {
		return nil, err
	}

	return &ibmKeyProtectClient{
		api:        api,
		instanceID: instanceId,
		baseURL:    baseUrl,
		tokenURL:   tokenUrl,
	}, nil
}

// createImportedKeyWithAliases imports the given base64-encoded payload as an extractable
// standard key with the provided aliases. It reports whether the key already existed (an alias
// conflict, HTTP 409), which the caller treats as success.
func (c *ibmKeyProtectClient) createImportedKeyWithAliases(ctx context.Context, name, payload string, aliases []string) (alreadyExists bool, err error) {
	body := map[string]interface{}{
		"metadata": map[string]interface{}{
			"collectionType":  ibmKeyProtectKeyType,
			"collectionTotal": 1,
		},
		"resources": []map[string]interface{}{
			{
				"type":        ibmKeyProtectKeyType,
				"name":        name,
				"extractable": true,
				"payload":     payload,
				"aliases":     aliases,
			},
		},
	}
	bodyJSON, err := json.Marshal(body)
	if err != nil {
		return false, errors.Wrap(err, "failed to build ibm key protect key create body")
	}

	opts := c.api.NewCreateKeyOptions(c.instanceID, io.NopCloser(bytes.NewReader(bodyJSON)))
	opts.SetPrefer(ibmKeyProtectReturnRepresentation)

	_, response, err := c.api.CreateKeyWithContext(ctx, opts)
	if err != nil {
		// A duplicate alias returns HTTP 409 Conflict (KEY_ALIAS_NOT_UNIQUE_ERR), which means
		// the key already exists.
		if response != nil && response.StatusCode == http.StatusConflict {
			return true, nil
		}
		return false, err
	}

	return false, nil
}

// getKey fetches a key (including its payload) by name or alias.
func (c *ibmKeyProtectClient) getKey(ctx context.Context, nameOrAlias string) (*kp.KeyWithPayload, error) {
	opts := c.api.NewGetKeyOptions(nameOrAlias, c.instanceID)

	result, _, err := c.api.GetKeyWithContext(ctx, opts)
	if err != nil {
		return nil, err
	}
	if result == nil || len(result.Resources) == 0 {
		return nil, errors.Errorf("ibm key protect returned no resources for key %q", nameOrAlias)
	}

	return &result.Resources[0], nil
}

// deleteKey force deletes a key by its ID.
func (c *ibmKeyProtectClient) deleteKey(ctx context.Context, id string) error {
	opts := c.api.NewDeleteKeyOptions(id, c.instanceID)
	opts.SetForce(true)
	opts.SetPrefer(ibmKeyProtectReturnRepresentation)

	_, _, err := c.api.DeleteKeyWithContext(ctx, opts)
	return err
}

// IsIBMKeyProtect determines whether the configured KMS is IBM Key Protect
func (c *Config) IsIBMKeyProtect() bool { return c.Provider == TypeIBM }
