---
# Service account for the Rook-Ceph operator
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-system
  namespace: {{ .Release.Namespace }} # namespace:operator
  labels:
    {{- include "library.rook-ceph.labels" . | nindent 4 }}
{{- include "library.imagePullSecrets" . | nindent 0 }}
---
# Service account for Ceph COSI driver
kind: ServiceAccount
apiVersion: v1
metadata:
  name: objectstorage-provisioner
  namespace: {{ .Release.Namespace }} # namespace:operator
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/name: cosi-driver-ceph
{{- include "library.imagePullSecrets" . | nindent 0 }}
