kind: BucketClaim
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: my-bucket
  namespace: my-namespace
spec:
  bucketClassName: odf-object-store-bucket
  protocols:
    - s3
---
kind: BucketAccess
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: my-bucket-access
  namespace: my-namespace
spec:
  bucketClaimName: my-bucket
  credentialsSecretName: my-bucket-credentials
  bucketAccessClassName: odf-object-store-access
  protocol: s3
