diff --git Makefile Makefile
index 5ccd6d28b..5fb204be2 100644
--- Makefile
+++ Makefile
@@ -119,7 +119,7 @@ build.version:
 	@echo "$(VERSION)" > $(OUTPUT_DIR)/version
 
 build.common: export SKIP_GEN_CRD_DOCS=true
-build.common: build.version helm.build mod.check crds gen-rbac
+build.common: build.version helm.build mod.check
 	@$(MAKE) go.init
 	@$(MAKE) go.validate
 	@$(MAKE) -C images/ceph list-image
