/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// ISCSIListerExpansion allows custom methods to be added to
// ISCSILister.
type ISCSIListerExpansion interface{}

// ISCSINamespaceListerExpansion allows custom methods to be added to
// ISCSINamespaceLister.
type ISCSINamespaceListerExpansion interface{}

// ISGWListerExpansion allows custom methods to be added to
// ISGWLister.
type ISGWListerExpansion interface{}

// ISGWNamespaceListerExpansion allows custom methods to be added to
// ISGWNamespaceLister.
type ISGWNamespaceListerExpansion interface{}

// NFSListerExpansion allows custom methods to be added to
// NFSLister.
type NFSListerExpansion interface{}

// NFSNamespaceListerExpansion allows custom methods to be added to
// NFSNamespaceLister.
type NFSNamespaceListerExpansion interface{}

// S3ListerExpansion allows custom methods to be added to
// S3Lister.
type S3ListerExpansion interface{}

// S3NamespaceListerExpansion allows custom methods to be added to
// S3NamespaceLister.
type S3NamespaceListerExpansion interface{}

// S3XListerExpansion allows custom methods to be added to
// S3XLister.
type S3XListerExpansion interface{}

// S3XNamespaceListerExpansion allows custom methods to be added to
// S3XNamespaceLister.
type S3XNamespaceListerExpansion interface{}

// SWIFTListerExpansion allows custom methods to be added to
// SWIFTLister.
type SWIFTListerExpansion interface{}

// SWIFTNamespaceListerExpansion allows custom methods to be added to
// SWIFTNamespaceLister.
type SWIFTNamespaceListerExpansion interface{}
