name: "Upterm debugging tests"
description: "Setup an upterm session for interactive debugging of failing tests"
inputs:
  debug-ci:
    description: "boolean for debug-ci label in PR"
    required: false
runs:
  using: "composite"
  steps:
    - name: consider upterm debugging
      shell: bash --noprofile --norc -eo pipefail -x {0}
      if: runner.debug || inputs.debug-ci == 'true'
      run: |
        # Enable upterm only in the main Rook repo, where the USE_TMATE secret is set in the repo, or if the action is re-run
        if [ "$GITHUB_REPOSITORY_OWNER" = "rook" ] || [ "$GITHUB_RUN_ATTEMPT" -gt 1 ]; then
          echo ENABLE_UPTERM=1 >> "$GITHUB_ENV"
        fi

    - name: set up upterm session
      if: ${{ env.ENABLE_UPTERM }}
      uses: owenthereal/action-upterm@f26ebc11e22a09b8365f39d2cdafd06f63b42053 # v1.14.0
      with:
        ## Pin the version of upterm used by the action:
        upterm-version: v0.26.0
        ## whether to limit ssh access and adds the ssh public key for the user which triggered the workflow:
        limit-access-to-actor: false
        ## If no one connects within five minutes, shut down the server:
        wait-timeout-minutes: 5
        detached: true
