/*
Copyright 2018 The Rook Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	cephrookiov1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CephObjectZoneGroupLister helps list CephObjectZoneGroups.
// All objects returned here must be treated as read-only.
type CephObjectZoneGroupLister interface {
	// List lists all CephObjectZoneGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cephrookiov1.CephObjectZoneGroup, err error)
	// CephObjectZoneGroups returns an object that can list and get CephObjectZoneGroups.
	CephObjectZoneGroups(namespace string) CephObjectZoneGroupNamespaceLister
	CephObjectZoneGroupListerExpansion
}

// cephObjectZoneGroupLister implements the CephObjectZoneGroupLister interface.
type cephObjectZoneGroupLister struct {
	listers.ResourceIndexer[*cephrookiov1.CephObjectZoneGroup]
}

// NewCephObjectZoneGroupLister returns a new CephObjectZoneGroupLister.
func NewCephObjectZoneGroupLister(indexer cache.Indexer) CephObjectZoneGroupLister {
	return &cephObjectZoneGroupLister{listers.New[*cephrookiov1.CephObjectZoneGroup](indexer, cephrookiov1.Resource("cephobjectzonegroup"))}
}

// CephObjectZoneGroups returns an object that can list and get CephObjectZoneGroups.
func (s *cephObjectZoneGroupLister) CephObjectZoneGroups(namespace string) CephObjectZoneGroupNamespaceLister {
	return cephObjectZoneGroupNamespaceLister{listers.NewNamespaced[*cephrookiov1.CephObjectZoneGroup](s.ResourceIndexer, namespace)}
}

// CephObjectZoneGroupNamespaceLister helps list and get CephObjectZoneGroups.
// All objects returned here must be treated as read-only.
type CephObjectZoneGroupNamespaceLister interface {
	// List lists all CephObjectZoneGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cephrookiov1.CephObjectZoneGroup, err error)
	// Get retrieves the CephObjectZoneGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*cephrookiov1.CephObjectZoneGroup, error)
	CephObjectZoneGroupNamespaceListerExpansion
}

// cephObjectZoneGroupNamespaceLister implements the CephObjectZoneGroupNamespaceLister
// interface.
type cephObjectZoneGroupNamespaceLister struct {
	listers.ResourceIndexer[*cephrookiov1.CephObjectZoneGroup]
}
