name: Commitlint
on:
  pull_request:
    branches:
      - master
      - release-*

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for wagoid/commitlint-github-action to get commits in PR
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: check out the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: lint commit messages
        run: |
          git fetch origin "${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}"
          if ! make lint.commits COMMITLINT_BASE=origin/${{ github.base_ref }}; then
            echo "See https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure for commit message requirements." >&2
            exit 1
          fi
