name: docs-check
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs-check:
    name: docs-check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26"

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.9

      - uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
        with:
          globs: |
            Documentation/**/*.md
            !Documentation/Helm-Charts

      - name: Check docs
        run: |
          make gen.docs
          tests/scripts/validate_modified_files.sh docs
      - name: Install mkdocs and dependencies
        run: cd build/release/ && make deps.docs

      - name: Check documentation for CRDs
        run: |
          make generate-docs-crds
          DIFF_ON_DOCS=$(git diff --ignore-matching-lines='on git commit')
          if [ -n "$DIFF_ON_DOCS" ]; then
          echo "Please run 'make generate-docs-crds' locally, commit the updated crds docs, and push the change"
          fi
          git diff --ignore-matching-lines='on git commit' --exit-code

      - name: Build documentation using mkdocs
        run: make docs-build
