name: Security scanning
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*

permissions:
  contents: read

jobs:
  security:
    if: github.repository == 'rook/rook'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "1.25"

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
        with:
          snyk-version: "v1.1302.1"

      - name: run Snyk to check for code vulnerabilities
        run: snyk test --debug
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GOFLAGS: "-buildvcs=false"
