name: Security scanning
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*

permissions:
  contents: read

jobs:
  security:
    if: github.repository == 'rook/rook'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.26"

      - name: Install Snyk CLI
        uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        with:
          snyk-version: "v1.1302.1"

      - name: run Snyk to check for code vulnerabilities
        run: snyk test --debug
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GOFLAGS: "-buildvcs=false"
